vim.wo.number = true                                  -- enable line numbers
vim.o.relativenumber = true                           -- set relative line number
vim.o.clipboard = "unnamedplus"                       -- sync neovim clipboard with system
vim.o.wrap = false                                    -- disable line wrapping
vim.o.linebreak = true                                -- dont split words either
vim.o.mouse = "a"                                     -- enable mouse (oh the horror!)
vim.o.autoindent = true                               -- enable auto indent
vim.o.breakindent = true                              -- enable break indent
vim.o.ignorecase = true                               -- enable case-insensitive searching..
vim.o.smartcase = true                                -- ..unless the search is specifically caps
vim.o.shiftwidth = 4                                  -- number of spaces for each indent
vim.o.tabstop = 4                                     -- insert x spaces per tab
vim.o.softtabstop = 4                                 -- convert x spaces into a tab
vim.o.expandtab = true                                -- convert tabs to spaces
vim.o.updatetime = 250                                -- decrease update time
vim.o.timeoutlen = 200                                -- time to wait for mapped sequence in ms
vim.o.completeopt = "menuone,noselect"                -- set autocomplete to be more pleasant
vim.o.whichwrap = "bs<>[]hl"                          -- characters that can travel between lines
vim.o.scrolloff = 4                                   -- minimum number of lines between cursor and edge
vim.o.sidescrolloff = 8                               -- minimum number of columns between cursor and edge
vim.o.smartindent = true                              -- enable smart indent
vim.o.swapfile = false                                -- disable swap file
vim.o.backspace = "indent,eol,start"                  -- allow backspace on
vim.o.backup = false                                  -- disable backup file
vim.o.writebackup = false                             -- allow multi-editing between other programs
vim.o.conceallevel = 0                                -- show '' in markdown
vim.o.cmdheight = 1                                   -- command menu height in lines
vim.o.pumheight = 10                                  -- size of pop-up menus in lines
vim.o.splitbelow = true                               -- force all horizontal splits below the cursor
vim.o.splitright = true                               -- force all vertical splits to right of cursor
vim.o.fileencoding = "utf-8"                          -- set filetype encoding
vim.o.autoindent = true                               -- copy indent from previous line
vim.opt.iskeyword:append("-")                         -- allow hyphenated words to work in searches
vim.opt.runtimepath:remove("/usr/share/vim/vimfiles") -- dont allow neovim to read vim plugins
vim.o.shell = '/usr/bin/bash'
