local paths = require("theme.icons.paths")
local dir = paths.theme_icons_dir

return {
	battery_alert = dir .. "widgets/battery/battery-alert.svg",
	battery_alert_red = dir .. "widgets/battery/battery-alert-red.svg",
	battery_unknown = dir .. "widgets/battery/battery-unknown.svg",
	discharging = {
		battery_0 = dir .. "widgets/battery/discharging/battery-0.svg",
		battery_5 = dir .. "widgets/battery/discharging/battery-5.svg",
		battery_10 = dir .. "widgets/battery/discharging/battery-10.svg",
		battery_15 = dir .. "widgets/battery/discharging/battery-15.svg",
		battery_20 = dir .. "widgets/battery/discharging/battery-20.svg",
		battery_25 = dir .. "widgets/battery/discharging/battery-25.svg",
		battery_30 = dir .. "widgets/battery/discharging/battery-30.svg",
		battery_35 = dir .. "widgets/battery/discharging/battery-35.svg",
		battery_40 = dir .. "widgets/battery/discharging/battery-40.svg",
		battery_45 = dir .. "widgets/battery/discharging/battery-45.svg",
		battery_50 = dir .. "widgets/battery/discharging/battery-50.svg",
		battery_55 = dir .. "widgets/battery/discharging/battery-55.svg",
		battery_60 = dir .. "widgets/battery/discharging/battery-60.svg",
		battery_65 = dir .. "widgets/battery/discharging/battery-65.svg",
		battery_70 = dir .. "widgets/battery/discharging/battery-70.svg",
		battery_75 = dir .. "widgets/battery/discharging/battery-75.svg",
		battery_80 = dir .. "widgets/battery/discharging/battery-80.svg",
		battery_85 = dir .. "widgets/battery/discharging/battery-85.svg",
		battery_90 = dir .. "widgets/battery/discharging/battery-90.svg",
		battery_95 = dir .. "widgets/battery/discharging/battery-95.svg",
		battery_100 = dir .. "widgets/battery/discharging/battery-100.svg",
	},
	charging = {
		battery_charging_0 = dir .. "widgets/battery/charging/battery-charging-0.svg",
		battery_charging_5 = dir .. "widgets/battery/charging/battery-charging-5.svg",
		battery_charging_10 = dir .. "widgets/battery/charging/battery-charging-10.svg",
		battery_charging_15 = dir .. "widgets/battery/charging/battery-charging-15.svg",
		battery_charging_20 = dir .. "widgets/battery/charging/battery-charging-20.svg",
		battery_charging_25 = dir .. "widgets/battery/charging/battery-charging-25.svg",
		battery_charging_30 = dir .. "widgets/battery/charging/battery-charging-30.svg",
		battery_charging_35 = dir .. "widgets/battery/charging/battery-charging-35.svg",
		battery_charging_40 = dir .. "widgets/battery/charging/battery-charging-40.svg",
		battery_charging_45 = dir .. "widgets/battery/charging/battery-charging-45.svg",
		battery_charging_50 = dir .. "widgets/battery/charging/battery-charging-50.svg",
		battery_charging_55 = dir .. "widgets/battery/charging/battery-charging-55.svg",
		battery_charging_60 = dir .. "widgets/battery/charging/battery-charging-60.svg",
		battery_charging_65 = dir .. "widgets/battery/charging/battery-charging-65.svg",
		battery_charging_70 = dir .. "widgets/battery/charging/battery-charging-70.svg",
		battery_charging_75 = dir .. "widgets/battery/charging/battery-charging-75.svg",
		battery_charging_80 = dir .. "widgets/battery/charging/battery-charging-80.svg",
		battery_charging_85 = dir .. "widgets/battery/charging/battery-charging-85.svg",
		battery_charging_90 = dir .. "widgets/battery/charging/battery-charging-90.svg",
		battery_charging_95 = dir .. "widgets/battery/charging/battery-charging-95.svg",
		battery_charging_100 = dir .. "widgets/battery/charging/battery-charging-100.svg",
	},
}
