configpath: /home/bmorin/.config/nom/config.yml
version: ""
feeds:

database: nom.db
ordering: asc
filtering:
    defaultIncludeFeedName: false
theme:
    glamour: dark
    titleColor: "62"
    titleColorFg: "231"
    filterColor: "62"
    selectedItemColor: "170"
    readIcon: ✓
http:
    mintls: TLS 1.2
